# Generated by Django 6.0.5 on 2026-07-02 21:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("animals", "0006_animal_date_of_death_animal_memorial_note"),
        ("users", "0004_profile_discord_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("schema_version", models.PositiveIntegerField()),
                ("source_revision", models.CharField(max_length=64)),
                ("allowed_categories_json", models.JSONField(blank=True, default=list)),
                (
                    "storage_backend",
                    models.CharField(
                        choices=[("local_private", "Local private filesystem")], default="local_private", max_length=32
                    ),
                ),
                ("storage_key", models.CharField(max_length=500)),
                ("file_size_bytes", models.PositiveBigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("ready", "Ready"), ("building", "Building"), ("failed", "Failed")],
                        default="building",
                        max_length=10,
                    ),
                ),
                ("error_message", models.CharField(blank=True, default=None, max_length=2500, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("superseded_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="offline_snapshots", to="animals.animal"
                    ),
                ),
                (
                    "generated_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="offline_snapshots", to="users.profile"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("animal", "generated_for"),
                        name="uniq_current_snapshot_per_animal_profile",
                    )
                ],
            },
        ),
    ]
