# Generated by Django 6.0.5 on 2026-07-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offline_snapshots", "0001_create_animal_snapshot_registry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalsnapshot",
            name="storage_key",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
