# Generated by Django 6.0.5 on 2026-07-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offline_snapshots", "0002_add_unique_storage_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="animalsnapshot",
            name="build_finished_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="animalsnapshot",
            name="build_started_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="animalsnapshot",
            name="task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
