# Generated by Django 6.0.5 on 2026-07-03 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0006_animal_date_of_death_animal_memorial_note"),
        ("offline_snapshots", "0003_add_task_id_and_build_timestamps"),
        ("users", "0004_profile_discord_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnapshotDownloadLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "outcome",
                    models.CharField(
                        choices=[("success", "Success"), ("forbidden", "Forbidden"), ("not_found", "Not found")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot_download_logs",
                        to="animals.animal",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot_download_logs",
                        to="users.profile",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="download_logs",
                        to="offline_snapshots.animalsnapshot",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["animal", "-created_at"], name="offline_sna_animal__0d5c75_idx"),
                    models.Index(fields=["created_at"], name="offline_sna_created_d2ff21_idx"),
                ],
            },
        ),
    ]
