# Generated by Django 4.2.1 on 2023-12-28 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medical_notes", "0005_medicalrecordattachment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalrecordattachment",
            name="description",
        ),
    ]
