# Generated by Django 6.0.5 on 2026-05-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical_notes", "0014_alter_discordnotification_last_modification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedingnote",
            name="purchase_source",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
