# Generated by Django 6.0.5 on 2026-06-02 20:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical_notes", "0015_add_feeding_note_purchase_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="VaccinationNote",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("vaccine_name", models.CharField(max_length=120)),
                ("last_vaccination_date", models.DateField(blank=True, default=None, null=True)),
                ("valid_until", models.DateField(blank=True, default=None, null=True)),
                ("suggested_clinic", models.CharField(blank=True, default="", max_length=250)),
                ("reminder_date", models.DateField(blank=True, db_index=True, default=None, null=True)),
                ("reminder_sent", models.BooleanField(default=False)),
                (
                    "related_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccination_records",
                        to="medical_notes.medicalrecord",
                    ),
                ),
            ],
        ),
    ]
