# Generated by Django 6.0.5 on 2026-06-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_pinned_animals"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="discord_user_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Discord user snowflake ID for notification delivery. Leave blank to disable Discord reminders.",
                max_length=32,
            ),
        ),
    ]
