---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: couchdb-credentials
  namespace: ahc
spec:
  encryptedData:
    COUCHDB_PASSWORD: AgA1c9v+1xdURnGWJiM7s8rAdf2ZSCfQwbOOZWNmQZglELSvGDK0kf+beiO7BdTqajoipqsqT6VKALK2hiwvNY2E8MW6Dy2OrO4n+wF9PzxpPf+6iYLG2uEzp73oNMZDyQQiJ12RJVSBoqcMBPtqzes8en6VGGaCruhPEGLT8L29ZTi6iRdm6599ELSXqKbDNU9gE9bki3RKx+ewTMYm34HPCCcbYf2qUt7FKEUzunM33LBlRd+R6BIaOXeB7D0DvkppS0p9wGD/eNFGkoAnP8Y7zs7Ie+FmrOvsTWfeNSsA/Umw/na9uyYeveEoWscOUpgTRO90yU4YEgPMpNrR5huETWVhaWCGG9xenxtumKiGQr1EHu4D2DjmS3wICv/kdHZVyCC22qfPxxcWJPg3Aagi+/ltt47qF6z3XEor8uJDxDdSMELGVlfAr4u+45zWzg85+HsNYLfLCrdW+ikvoDHEeAyaPQ+QjQ+DGFopRr6HO3KVS+lx+4rI9FsfzDm0IJHT3ZdbP2/8SUYlBclyr/cDacFaFTt5JH9QYBpsnRK7LunQNsb0oeNGhUydc/kTfOhT5dFzXssxbH+iw3kzrBJBeSZnU2YzmdxuaA+OuftHUlPZJSViO73uTTOBam8l1EX4si6JGrz2a93O7/EqEIxyztMpf5QqvRM88u/j0ID8Zn3oCONIwMgsRCpRylv2zyu3GQuHRl4=
    COUCHDB_USER: AgBnPO2qGM6rRIk5dr3ABx5pbaRiLuvjAqBTjkGgdjEnePReF9h3f0ClYMvRsVgoOCLv4Oqekc7IMA2RJTtS6JAQKKoC8VQcUcU/ChMkU6KwdmM3IYKPdYysPmIJYU29Hc/epSjIQgF48w0ZFAEI1nmxR1wb1G34+rK2wTK58oT02cCzPug6+3RUTaAKVIQfYgK/iGakRUB9+yro0DWIUeW0IHI1FDgaLZaGLeRW2otRkLwf6E4vNzQ9AO9S+ylM7RmkSFZc7PDOq79zxyN51Zx+Yr+mi8E6DBfYS8cB/55us16LUYOReammGTrWCPsC0/fANnDcHB2n+9DXDFW7AL39Rq7yRTuwAuJpU3TN5iwx9sIGi65mrY5w7q5+0o2cQPP6dcLUv66oqNxXu5CgO29wp4Go5U6nxLgUDlC1ZPiEROr4g6iqqm5jCyg3prxe3Tz3gbRiAzzmpu+wRmETZe2ADZ8giUWfmbbKT6SQbQnnBcX7EdMEQbGtJAKIKkwwVVtSbF5VFS1OnXG1QYFnYt7lQqHDEV4URwcPp5uy+tpBSa87Y0Jduv75Xwh0JwhxFjEvc8V6PjpDr6WGgssv3J5iNOYtD3bmYJi7Fhyd7YwXl6ZFVM0VeqtKL9h4LQcpDMN5zr3UBiD91lfqcXOnTcdPn7fK7/MNuPhQxAVUxSMVo0JL4mxJzqffvgvWNvia7+d81DkJQOU=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-3"
      name: couchdb-credentials
      namespace: ahc
