---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flower-secrets
  namespace: ahc
spec:
  encryptedData:
    FLOWER_BASIC_AUTH: AgAxvpf+PAZxz/6E247zQC/dZBZmUDEMFBxiMJOJlGO7mXcyfKzbrfOGHXZRYgV9r0LYRv8i0C5SXTpxHkZbHqh1sKg0/OvjgcdZvJIF5UctD7QkenN5A4ney3m7NGnB9SWjcX5Fw0Jaw7W6DhNgwaqmZI5tD6RvI6LUg7JYqpERtbhn2B5KcrE7Qhn8yc3HtskOzOWp4sZT9cC6/UrCY6mqOAtK56B4Z5p53vOq1T+zEDo1qODWyNO2g9ILi7z8ua9G5677O8hphuqIB4khJDxL/HKpqzX9Z25asTm2UgN1zSHwA4xaLIBp4Q9IAOEtH5mDCnU7+1ntggJXFTkfh8fxdQ9u1dL+oWf8mqlELrsqqSfqVeoHLrrmZHSMQQG0A8T8ZiSIpM2SLL6tlC75KxzdQ0ZlFMk6No9nXFtcA1teYY0xVP1bKz+FVR7ZBEUYltGfNXCvag3b2IEQuaq3o8nI55I3qjUvevTgvwBUH1Uj6HISaZfnJactyI+Sne8GjkzFLE+OD2l3okTXkg0BkSd5Sygwf9pg9X3PLhwqtz2HC0WQ8JmG3zmzTAsEaA6iB4sLgIWx5eUoXNmTZhBvKEJQJwX0HNTz4aPmYGOFoX+1JqTp4NQXwFfGoPgb/WlCLUps7WyPV8A0g59lcr+Gb9OaxX5Qw9zXDJ/t/JWr/QRsIMSzRlR2djNc0TWhxlJN4Am5k+lJq26J2pAaCw==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-3"
      name: flower-secrets
      namespace: ahc
