repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
        exclude: '\.sh$'
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
    -   id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        types: [python]
        require_serial: true
        args: ['--in-place', '--remove-all-unused-imports']
        exclude: '^requirements\.txt$|^setup_couchdb\.sh$'
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ['--profile', 'black', '--lines-between-types', '1', '--filter-files']
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        language_version: python3.12
        args: ['--line-length', '120']
