FROM python:3.12
LABEL authors="AM"
WORKDIR /app
COPY Pipfile Pipfile.lock ./

RUN python -m pip install --upgrade pip &&  \
    pip install --no-cache-dir pipenv &&  \
    pipenv install --dev --system --deploy

COPY . .
