# Generated by Django 4.2.1 on 2023-10-06 16:41

from django.db import migrations, models

import ahc.apps.homepage.utils


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilebackground",
            name="content",
            field=models.ImageField(
                default=ahc.apps.homepage.utils.ImageGenerator.default_profile_image,
                upload_to="static/media/background",
            ),
        ),
    ]
