# Generated by Django 6.0.5 on 2026-06-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0004_delete_cronjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilebackground",
            name="content",
            field=models.ImageField(blank=True, default="", upload_to="static/media/background"),
        ),
    ]
