---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: couchdb-credentials
  namespace: ahc
spec:
  encryptedData:
    COUCHDB_PASSWORD: AgBLcq7HVmCbUPN7qqLRtgsBtsM+foW5oj6TGra+BWGKQG+AAcZCp8wMFgkqMov4LvYDJHXnG0JII7AAnZBy8PpHk9hmMSxYyI30TfjKsNdvPDRvQepakbWeJs1nW6oPFgoXDuu8y18fKLc+ETnwxzcjwcr26gqt7Vm5JxgiwBbCcAl+0HyUXNtx1hJkm1sLi/OM/ZczTIYC5fO3/9iPmfg9GgtKI2l5LZOLKj00ItGny2qpaufUwHYC8EW7w1VTtBe93CntZJteTWaXpMr535yihZgV3DufB+wlQUct74SoJvwhzgeQn89WoUQKjmlF5n1LgSFHpMr9IQxZl9ort7mnBVErcbnHAgvzC0/nwQLOqeTL6a8pULoggnlZt/hwCu1ZRFg3Rz0EiffffwEDDD56ERt9AnnIATTSz1Pe4VEw6I7d/ov4JhI+NiLvbuIW4zSGa7RCqS4+rcVw+KyfIMNlXAcjNWopHO72QAi9nK7jx68sRq6RzunYgSiKqJNsnjMkH3Qlqy42vMhd448FjDp6wZWZETTIWYiA1754IQtyhJuEwtZfm8VmRkfeSBEBKEAl5q/jQskceX9PJKRW9bdSamGD/RXPmG6+IuvHdwLZOe/ptAQel59j6n8y/joG6osVYN+nn50EJrfnqjTUAF+z36e2uCqp6msfj/Luc4KjGHhlbJjx86gzxkGYidaS130tJxLZTjs=
    COUCHDB_USER: AgCU+DwkpeQBDdpjxWc4t2niyVicMQWIa1x8Dyf2OVs5X3Yi26rgfScasgEuUqvnQ4UusZOKa6/f7jSoTaxesBDPQgPLOwg/X2v6lmJq9Mnoi9wD3iy+cs3IjkGherhNn009gNo85Wh1nnmg/00e3MN6rKDEEGiHB+9rTSG4OIX5ycvfakhqNi5sz/FYgOJazU+g4+qPkgBsQAtKjI4njUB/dVxYgQF9IQV5nNi3Jruo9s7Rn2PfBgz9I78syKkrzSb7N7KbuG6NnPQAeQsohqkDx3ULA+QaoTYrnNqHB+N66IlCLYtRH/5w1QHAJbk80Ysp87ucP2OxbmP/07ZdrgDljl8Z2qBE5szLLPJzhEPkJqtonf8vJxi+6RFmC8mrCxktxDz4VBggYzcrQQtZal4f9zps4NnSOYWqlUa657TcSNmnKxFGOnyI7THVJRo9mNT0Ik/T3ETcs9bA2TqjjFRS/rMWGcmqQSM4QE1yfMJZSzuuw2KRv33WXYYOQEH2EHhr6kc5xM9p1oRTtcf1BhvhXm/90yeXJosL2wfARGxELEitO57o08JCjOr1YX/3pCepJCb0JeyGLK84BGT/WoebTQCnxlEur/CuaEVjC3HFYawlvjMXhdVrZtqyKUyJZE664qlDl/ezq9WKAMgw3Sk6mUowWeZdQR8vYAqa0MCxrlnzQZF1YL6I1PVVGcxRGzmTBGHWB7w=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-3"
      creationTimestamp: null
      name: couchdb-credentials
      namespace: ahc
