---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flower-secrets
  namespace: ahc
spec:
  encryptedData:
    FLOWER_BASIC_AUTH: AgB51xcbMBCKjaOBUwY0f3K+M9yvXfc99Bdg73riTowf+GYCvI08CFIVq5DEwBDBXlvFVYhhMeLm74tYJlnURk0OAjP8O/KGXC2asNKWI3hKjEz+CKqEyG5p9/zQKcPuT/JehDwNQQGRa2zubphuKySEcoxlvac2GOVn9epkS8ECxxR94Yd8pkOxJ2xitnyRhY1fDZl9ncMIFC2oBE/9iYfVKsX71tCWByFiS2WwDK+W3VmwngFvdBgQVRNuQ7TZBKPKG5XSUiz+VVXrp15HKfD66S8CiwEsbVl/4BNeIVZB7fN0ILlvNcVspiOJpJt+BrCzCuQQdJQ88sotFMKJ+hmEAZme7FGIyerfqKK8hJd/455Md6UF/5aaVq9f1uGYhYDoSu1aFi1uQTtT62eCqEeBxLmKpLEUfrUfVCVYT4fPA2FnXuu5yaajiZ62ynd/y43NmQ4ecjW78qbym+2QuP3gAzCdjdp7t2ZoAmKkxUlwxNxxbur+c/9vpRM6JuVhVlemXR6Ndcw9ydD1qNorsjyjeeIjPzsPpF0SS4WeVqJlo3dIUZZRzJBI3/cgx05nCPXUAu7namwCIQAps2hNm7tIuuuLMAMTXJ9k0BQTVYSYxLJrtRFFYGK8zXMFPHpQw+lxcv+8PK753bkRaKsFu0AnNEPMU5broNX2uZIyVQcKiYkFjiO7TsG1h/0dTl84rmKCcMzawGKI1zOgKQ==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-3"
      creationTimestamp: null
      name: flower-secrets
      namespace: ahc
