# Generated by Django 4.2.1 on 2023-07-19 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Privilege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("privelage_to_delete_animal", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ProfileBackground",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                (
                    "content",
                    models.ImageField(
                        default="AHC_app/static/media/icons/chinchilla.png",
                        upload_to="AHC_app/static/media/animal_pic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimalTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                (
                    "content",
                    models.ImageField(
                        default="AHC_app/static/media/icons/chinchilla.png",
                        upload_to="AHC_app/static/media/animal_pic",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
