# Generated by Django 4.2.1 on 2023-07-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilebackground",
            name="content",
            field=models.ImageField(
                default="AHC_app/static/media/background/background-1169534_1920.png",
                upload_to="AHC_app/static/media/background",
            ),
        ),
    ]
