# Generated by Django 4.2.1 on 2023-10-06 16:41

import homepage.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilebackground",
            name="content",
            field=models.ImageField(
                default=homepage.utils.ImageGenerator.default_profile_image,
                upload_to="static/media/background",
            ),
        ),
    ]
