import json
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError

from ahc.apps.offline_snapshots.services.inspector import SnapshotInspectionError, inspect_snapshot
from ahc.apps.offline_snapshots.services.schema import SCHEMA_VERSION


class Command(BaseCommand):
    help = "Validate an exported animal snapshot file and print its manifest and per-table row counts (ADR-12)."

    def add_arguments(self, parser):
        parser.add_argument("path", help="Path to an exported snapshot .db file")
        parser.add_argument("--json", action="store_true", help="Print the report as JSON instead of plain text")
        parser.add_argument(
            "--driver",
            choices=["sqlite", "libsql"],
            default="sqlite",
            help="Driver to use for reading the snapshot (default: sqlite)",
        )
        parser.add_argument(
            "--compare-drivers",
            action="store_true",
            help="Compare sqlite3 and libSQL output and print a parity report",
        )

    def handle(self, *args, **options):
        path = Path(options["path"])

        if options["compare_drivers"]:
            self._handle_compare_drivers(path)
            return

        if options["driver"] == "libsql":
            self._handle_libsql(path)
            return

        try:
            report = inspect_snapshot(path)
        except SnapshotInspectionError as exc:
            raise CommandError(str(exc)) from exc

        if options["json"]:
            self.stdout.write(json.dumps(report, indent=2))
            return

        self.stdout.write(f"Snapshot: {report['path']}")
        self.stdout.write(f"  Animal ID: {report['animal_id']}")
        self.stdout.write(f"  Schema version: {report['schema_version']}")
        self.stdout.write(f"  Exporter version: {report['exporter_version'] or 'unknown'}")
        self.stdout.write(f"  Source revision: {report['source_revision']}")
        self.stdout.write(f"  Generated at: {report['generated_at']}")
        self.stdout.write(f"  Generated by: {report['generated_by'] or 'unknown'}")
        self.stdout.write(f"  Read-only: {'yes' if report['is_read_only'] else 'no'}")
        self.stdout.write("Row counts:")
        for table, count in report["row_counts"].items():
            self.stdout.write(f"  {table}: {count}")
        self.stdout.write(self.style.SUCCESS(f"Snapshot OK (schema_version={report['schema_version']})."))

    def _handle_libsql(self, path: Path) -> None:
        from ahc.apps.offline_snapshots.services.driver_parity import read_snapshot_libsql

        try:
            result = read_snapshot_libsql(path)
        except Exception as exc:
            raise CommandError(str(exc)) from exc

        m = result.manifest
        self.stdout.write(f"Snapshot: {path}")
        self.stdout.write(f"  Animal ID: {m['animal_id']}")
        self.stdout.write(f"  Schema version: {m['schema_version']}")
        self.stdout.write(f"  Exporter version: {m.get('exporter_version') or 'unknown'}")
        self.stdout.write(f"  Source revision: {m['source_revision']}")
        self.stdout.write(f"  Generated at: {m['generated_at']}")
        self.stdout.write(f"  Generated by: {m.get('generated_by') or 'unknown'}")
        self.stdout.write(f"  Read-only: {'yes' if m['is_read_only'] else 'no'}")
        self.stdout.write("Row counts:")
        for table, count in result.row_counts.items():
            self.stdout.write(f"  {table}: {count}")
        self.stdout.write(self.style.SUCCESS(f"Snapshot OK (schema_version={SCHEMA_VERSION})."))

    def _handle_compare_drivers(self, path: Path) -> None:
        from ahc.apps.offline_snapshots.services.driver_parity import compare_drivers

        try:
            report = compare_drivers(path)
        except Exception as exc:
            raise CommandError(str(exc)) from exc

        s = report.sqlite_read.manifest
        l = report.libsql_read.manifest  # noqa: E741

        self.stdout.write(f"Snapshot: {path}")
        self.stdout.write("")
        self.stdout.write(
            f"{'sqlite3':<9} manifest:"
            f"  schema_version={s['schema_version']}"
            f"  animal_id={s['animal_id']}"
            f"  source_revision={s['source_revision']}"
        )
        self.stdout.write(
            f"{'libSQL':<9} manifest:"
            f"  schema_version={l['schema_version']}"
            f"  animal_id={l['animal_id']}"
            f"  source_revision={l['source_revision']}"
        )
        self.stdout.write(f"Manifest parity: {'OK' if report.manifest_diff is None else 'DIFF'}")
        self.stdout.write("")
        self.stdout.write("Row counts (sqlite3 / libSQL):")
        for table, sqlite_count in report.sqlite_read.row_counts.items():
            libsql_count = report.libsql_read.row_counts[table]
            self.stdout.write(f"  {table + ':':44} {sqlite_count} / {libsql_count}")
        self.stdout.write(f"Row count parity: {'OK' if report.row_count_diff is None else 'DIFF'}")
        self.stdout.write(f"Row data parity: {'OK' if report.row_data_diff is None else 'DIFF'}")
        self.stdout.write("")
        self.stdout.write(f"PRAGMA integrity_check (sqlite3): {'OK' if report.integrity_ok else 'FAIL'}")
        parity_label = "OK" if report.ok else "FAIL"
        if report.ok:
            self.stdout.write(self.style.SUCCESS(f"Driver parity: {parity_label}"))
        else:
            self.stdout.write(self.style.ERROR(f"Driver parity: {parity_label}"))
