import json
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError

from ahc.apps.offline_snapshots.services.inspector import SnapshotInspectionError, inspect_snapshot


class Command(BaseCommand):
    help = "Validate an exported animal snapshot file and print its manifest and per-table row counts (ADR-12)."

    def add_arguments(self, parser):
        parser.add_argument("path", help="Path to an exported snapshot .db file")
        parser.add_argument("--json", action="store_true", help="Print the report as JSON instead of plain text")

    def handle(self, *args, **options):
        try:
            report = inspect_snapshot(Path(options["path"]))
        except SnapshotInspectionError as exc:
            raise CommandError(str(exc)) from exc

        if options["json"]:
            self.stdout.write(json.dumps(report, indent=2))
            return

        self.stdout.write(f"Snapshot: {report['path']}")
        self.stdout.write(f"  Animal ID: {report['animal_id']}")
        self.stdout.write(f"  Schema version: {report['schema_version']}")
        self.stdout.write(f"  Exporter version: {report['exporter_version'] or 'unknown'}")
        self.stdout.write(f"  Source revision: {report['source_revision']}")
        self.stdout.write(f"  Generated at: {report['generated_at']}")
        self.stdout.write(f"  Generated by: {report['generated_by'] or 'unknown'}")
        self.stdout.write(f"  Read-only: {'yes' if report['is_read_only'] else 'no'}")
        self.stdout.write("Row counts:")
        for table, count in report["row_counts"].items():
            self.stdout.write(f"  {table}: {count}")
        self.stdout.write(self.style.SUCCESS(f"Snapshot OK (schema_version={report['schema_version']})."))
