"""
Django's settings for AHC_app project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import sys
from pathlib import Path

from decouple import Csv, config

_OFFLINE_COMMANDS = {
    "check",
    "collectstatic",
    "crontab",
    "makemigrations",
    "migrate",
    "shell",
    "showmigrations",
    "sqlmigrate",
    "test",
}


def _is_test_run() -> bool:
    return "test" in sys.argv or (bool(sys.argv) and "pytest" in sys.argv[0])


def _skip_external_services() -> bool:
    """Return True when live network backends (CouchDB) must not be initialised.

    Covers: pytest invocations, manage.py test, and any manage.py command that
    does not require a running CouchDB connection at import time.
    """
    return _is_test_run() or any(cmd in sys.argv for cmd in _OFFLINE_COMMANDS)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parents[2]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

if _is_test_run():
    SECRET_KEY = config("SECRET_KEY", default="django-insecure-test-only-not-for-production")
    DEBUG = True
else:
    SECRET_KEY = config("SECRET_KEY")
    DEBUG = config("DEBUG", default=False, cast=bool)
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1", cast=Csv())


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "taggit",
    "ahc.apps.homepage.apps.HomepageConfig",
    "ahc.apps.users.apps.UsersConfig",
    "ahc.apps.animals.apps.AnimalsConfig",
    "ahc.apps.medical_notes.apps.MedicalNotesConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.csp.ContentSecurityPolicyMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ahc.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # 'DIRS': [],
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "ahc.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if _is_test_run():
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": "mydatabase",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DB_NAME"),
            "USER": config("DB_USER"),
            "PASSWORD": config("DB_PASSWORD"),
            "HOST": config("DB_HOST"),
            "PORT": config("DB_PORT", default="5432"),
        }
    }

# COUCH_CONNECTOR = (config("COUCH_CONNECTOR"),)

if not _skip_external_services():
    COUCHDB_USER = config("COUCHDB_USER")
    COUCHDB_PASSWORD = config("COUCHDB_PASSWORD")
    COUCHDB_PORT = config("COUCHDB_PORT")
    COUCHDB_HOST = config("COUCHDB_HOST", default="appendixes-db")
    COUCHDB_DB_NAME = config("COUCHDB_DB_NAME", default="appendixes")
    COUCHDB_BASE_URL = f"http://{COUCHDB_HOST}:{COUCHDB_PORT}"

    COUCH_DB_LIMIT_PER_NOTE = 5


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOGIN_REDIRECT_URL = "Homepage"
LOGIN_URL = "login"


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Warsaw"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static_collected"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

_staticfiles_backend = (
    "django.contrib.staticfiles.storage.StaticFilesStorage"
    if _is_test_run()
    else "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"
)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": _staticfiles_backend,
    },
}

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "static" / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


CELERY_BROKER_URL = config("CELERY_BROKER_URL")
CELERY_BACKEND = config("CELERY_BACKEND")


EMAIL_BACKEND = config("EMAIL_BACKEND")
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=False, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")

DISCORD_TOKEN = config("DISCORD_TOKEN")

TEST_RUNNER = "django.test.runner.DiscoverRunner"

from django.utils.csp import CSP  # noqa: E402

SECURE_CSP = {
    "default-src": [CSP.SELF],
    "script-src": [CSP.SELF],
    "style-src": [CSP.SELF, CSP.UNSAFE_INLINE, "https://fonts.googleapis.com"],
    "img-src": [CSP.SELF, "data:"],
    "font-src": [CSP.SELF, "https://fonts.gstatic.com"],
    "connect-src": [CSP.SELF],
    "object-src": [CSP.NONE],
    "base-uri": [CSP.SELF],
}
SECURE_CSP_REPORT_ONLY = SECURE_CSP

TASKS = {
    "default": {
        "BACKEND": "django.tasks.backends.immediate.ImmediateBackend",
    },
}
