apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres_db
  labels:
    app: postgres_db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres_db
  template:
    metadata:
      name: postgres_db
      labels:
        app: postgres_db
    spec:
      containers:
        - name: postgres_db
          image: postgres_db:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - secretRef:
                name: secrets
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
      restartPolicy: Always
