apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  labels:
    app: postgres_db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres_db
  template:
    metadata:
      name: postgres-db
      labels:
        app: postgres_db
    spec:
      containers:
        - name: postgres-db
          image: postgres:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5433
              protocol: TCP
          envFrom:
            - secretRef:
                name: postgres-secrets
#          volumeMounts:
#            - mountPath: /var/lib/postgresql/data
#              name: postgresdata
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
      restartPolicy: Always
