apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ahc-home
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Cybernetic-Ransomware/Animals_Healthcare_Application.git
    targetRevision: main
    path: kubernetes/overlays/home
  destination:
    server: https://kubernetes.default.svc
    namespace: ahc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
