# Generated by Django 4.2.1 on 2023-10-06 16:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                (
                    "short_description",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "long_description",
                    models.CharField(
                        blank=True, default=None, max_length=2500, null=True
                    ),
                ),
                ("birthdate", models.DateField(default=None, null=True)),
                (
                    "profile_image",
                    models.ImageField(
                        default="profile_pics/pet-care.png",
                        upload_to="profile_pics/animals",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "first_contact_vet",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "first_contact_medical_place",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                ("last_control_visit", models.DateTimeField(default=None, null=True)),
                (
                    "allowed_users",
                    models.ManyToManyField(related_name="keepers", to="users.profile"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owner",
                        to="users.profile",
                    ),
                ),
            ],
        ),
    ]
