# Generated by Django 4.2.1 on 2023-08-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='birthdate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='first_contact_medical_place',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='animal',
            name='first_contact_vet',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='animal',
            name='last_control_visit',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='long_description',
            field=models.CharField(blank=True, default=None, max_length=2500),
        ),
        migrations.AlterField(
            model_name='animal',
            name='short_description',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
    ]
