# Generated by Django 4.2.1 on 2023-08-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='first_contact_medical_place',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='first_contact_vet',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='long_description',
            field=models.CharField(blank=True, default=None, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='short_description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
