# Generated by Django 4.2.1 on 2023-09-11 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_animal_first_contact_medical_place_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
