# Generated by Django 4.2.1 on 2023-09-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_delete_medicalrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometricrecord',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='currentdiet',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='currentmedicine',
            name='animal',
        ),
        migrations.DeleteModel(
            name='BiometricCustomRecords',
        ),
        migrations.DeleteModel(
            name='BiometricRecord',
        ),
        migrations.DeleteModel(
            name='CurrentDiet',
        ),
        migrations.DeleteModel(
            name='CurrentMedicine',
        ),
    ]
