apiVersion: apps/v1
kind: Deployment
metadata:
  name: couch_db
  labels:
    app: couch_db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couch_db
  template:
    metadata:
      name: couch_db
      labels:
        app: couch_db
    spec:
      containers:
        - name: couch_db
          image: couch_db:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5984
              protocol: TCP
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
