apiVersion: apps/v1
kind: Deployment
metadata:
  name: couch-db
  labels:
    app: couch-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couch-db
  template:
    metadata:
      name: couch-db
      labels:
        app: couch-db
    spec:
      containers:
        - name: couch-db
          image: ahc_app-couch_db:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5982
              protocol: TCP
          envFrom:
            - secretRef:
                name: couchdb-secrets
          volumeMounts:
            - mountPath: /opt/couchdb/data
              name: couchdbdata
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: couchdbdata
          persistentVolumeClaim:
            claimName: couch-db-volume-claim
      restartPolicy: Always
