apiVersion: v1
kind: PersistentVolume
metadata:
  name: couch_db-volume
  labels:
    type: local
    app: couch_db
spec:
  storageClassName: local-couch_db
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: db/couchdb
