apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couch_db-volume-claim
  labels:
    app: couch_db
spec:
  storageClassName: local-couch_db
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
