apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
  labels:
    app: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      name: queue
      labels:
        app: queue
    spec:
      containers:
        - name: queue
          image: ahc_app-queue:latest
          imagePullPolicy: IfNotPresent
          command: [ "celery", "-A", "AHC_app.celery_notifications.config:celery_obj", "worker", "-l", "info" ]
          env:
            - name: DJANGO_SETTINGS_MODULE
              valueFrom:
                configMapKeyRef:
                  name: celery-config
                  key: DJANGO_SETTINGS_MODULE
          ports:
            - containerPort: 5000
              protocol: TCP
          envFrom:
            - secretRef:
                name: queue-secrets
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
