apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
  labels:
    app: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      name: queue
      labels:
        app: queue
    spec:
      containers:
        - name: queue
          image: queue:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
              protocol: TCP
          envFrom:
            - secretRef:
                name: ..secrets
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
