apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery_flower
  labels:
    app: celery_flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery_flower
  template:
    metadata:
      name: celery_flower
      labels:
        app: celery_flower
    spec:
      containers:
        - name: celery_flower
          image: celery_flower:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5555
              protocol: TCP
          envFrom:
            - secretRef:
                name: ..secrets
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
