# Generated by Django 4.2.1 on 2023-10-12 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(db_index=True, default=None, null=True)),
                ('profile_image', models.ImageField(default='profile_pics/signup2.png', upload_to='profile_pics/users')),
                ('privilege_tier', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.privilege')),
                ('profile_background', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.profilebackground')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
