# Generated by Django 4.2.1 on 2024-02-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="allow_recennt_animals_list",
            field=models.BooleanField(default=True),
        ),
    ]
