# Generated by Django 4.2.1 on 2023-07-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_profile_background"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birthdate",
            field=models.DateField(db_index=True, null=True),
        ),
    ]
