# Generated by Django 4.2.1 on 2023-07-20 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0003_alter_profilebackground_content"),
        ("users", "0004_alter_profile_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_background",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="homepage.profilebackground",
            ),
        ),
    ]
