# Generated by Django 4.2.1 on 2023-08-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_profile_profile_background"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                default="profile_pics/signup2.png", upload_to="profile_pics/users"
            ),
        ),
    ]
