# Generated by Django 4.2.1 on 2023-09-14 12:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0004_delete_medicalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_event_started', models.DateField(blank=True, null=True)),
                ('date_event_ended', models.DateField(blank=True, null=True)),
                ('participants', models.CharField(blank=True, max_length=80)),
                ('place', models.CharField(blank=True, max_length=80)),
                ('short_description', models.CharField(max_length=125)),
                ('full_description', models.CharField(blank=True, max_length=2500)),
                ('type_of_event', models.CharField(max_length=50)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
            ],
        ),
    ]
