# Generated by Django 4.2.1 on 2023-10-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical_notes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currentmedicine",
            name="animal",
        ),
        migrations.DeleteModel(
            name="CurrentDiet",
        ),
        migrations.DeleteModel(
            name="CurrentMedicine",
        ),
    ]
