# Generated by Django 4.2.1 on 2023-09-28 09:56

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('medical_notes', '0002_currentmedicine_currentdiet_biometricrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='note_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
