# Generated by Django 4.2.1 on 2023-11-02 10:29

import django.contrib.postgres.fields
import django.db.models.deletion
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "medical_notes",
            "0002_remove_currentmedicine_animal_delete_currentdiet_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedingNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("real_start_date", models.DateField(null=True)),
                ("real_end_date", models.DateField(null=True)),
                ("is_medicine", models.BooleanField(blank=True, default=False)),
                ("category", models.CharField(max_length=50)),
                ("product_name", models.CharField(max_length=80)),
                ("producer", models.CharField(max_length=120)),
                ("dose_annotations", models.CharField(max_length=250)),
                (
                    "related_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_notes.medicalrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SMSNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=250)),
                ("is_active", models.BooleanField(default=False)),
                ("receiver_name", models.CharField(max_length=30)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("timezone", timezone_field.fields.TimeZoneField(default="GTM")),
                ("daily_timestamp", models.TimeField(blank=True, null=True)),
                (
                    "days_of_week",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.BooleanField(blank=True, default=False),
                            size=1,
                        ),
                        size=7,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "country_code",
                    models.CharField(blank=True, default="+48", max_length=5),
                ),
                ("message", models.CharField(max_length=160)),
                (
                    "related_note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_notes.feedingnote",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmailNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=250)),
                ("is_active", models.BooleanField(default=False)),
                ("receiver_name", models.CharField(max_length=30)),
                ("message", models.CharField(max_length=2500)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("timezone", timezone_field.fields.TimeZoneField(default="GTM")),
                ("daily_timestamp", models.TimeField(blank=True, null=True)),
                (
                    "days_of_week",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.BooleanField(blank=True, default=False),
                            size=1,
                        ),
                        size=7,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "related_note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_notes.feedingnote",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DiscordNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=250)),
                ("is_active", models.BooleanField(default=False)),
                ("receiver_name", models.CharField(max_length=30)),
                ("message", models.CharField(max_length=2500)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("timezone", timezone_field.fields.TimeZoneField(default="GTM")),
                ("daily_timestamp", models.TimeField(blank=True, null=True)),
                (
                    "days_of_week",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.BooleanField(blank=True, default=False),
                            size=1,
                        ),
                        size=7,
                    ),
                ),
                ("user_id", models.PositiveBigIntegerField()),
                ("bot_id", models.PositiveBigIntegerField()),
                (
                    "related_note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_notes.feedingnote",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
