# Generated by Django 4.2.1 on 2023-12-28 16:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("medical_notes", "0004_alter_discordnotification_timezone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecordAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="static/media/attachments/")),
                ("description", models.CharField(blank=True, max_length=255)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="medical_notes.medicalrecord",
                    ),
                ),
            ],
        ),
    ]
