# Generated by Django 4.2.1 on 2023-09-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_notes', '0004_genericstringtaggeditem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericstringtaggeditem',
            name='object_id',
            field=models.CharField(db_index=True, max_length=80, verbose_name='Object id'),
        ),
    ]
