# Generated by Django 4.2.1 on 2023-09-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_notes', '0006_uuidtaggeditem_delete_genericstringtaggeditem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uuidtaggeditem',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
