# Generated by Django 4.2.1 on 2024-01-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical_notes", "0006_remove_medicalrecordattachment_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecordattachment",
            name="url",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
