# Generated by Django 4.2.1 on 2023-09-28 12:36

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('medical_notes', '0007_alter_uuidtaggeditem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='note_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='medical_notes.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
