# Generated by Django 4.2.1 on 2023-10-04 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_profile_image'),
        ('medical_notes', '0008_alter_medicalrecord_note_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
