# Generated by Django 4.2.1 on 2024-02-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_notes", "0010_alter_discordnotification_last_modification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecordattachment",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
