# Generated by Django 4.2.1 on 2024-02-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_notes", "0011_medicalrecordattachment_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecordattachment",
            name="file_name",
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AlterField(
            model_name="medicalrecordattachment",
            name="file",
            field=models.FileField(blank=True, upload_to="attachments/"),
        ),
    ]
