# Generated by Django 4.2.1 on 2024-02-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_notes", "0012_medicalrecordattachment_file_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalrecordattachment",
            name="url",
        ),
        migrations.AddField(
            model_name="medicalrecordattachment",
            name="couch_id",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
