# Generated by Django 4.2.1 on 2023-10-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_notes', '0013_biometricheightrecords_biometricweightrecords_and_more'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE medical_notes_biometriccustomrecords DROP COLUMN id CASCADE;'),
        migrations.RunSQL('ALTER TABLE medical_notes_biometriccustomrecords ADD COLUMN id SERIAL PRIMARY KEY;'),
        migrations.RunSQL('ALTER TABLE medical_notes_biometricrecord DROP COLUMN id CASCADE;'),
        migrations.RunSQL('ALTER TABLE medical_notes_biometricrecord ADD COLUMN id SERIAL PRIMARY KEY;'),
    ]
