# Generated by Django 4.2.1 on 2024-02-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_notes", "0013_remove_medicalrecordattachment_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordnotification",
            name="last_modification",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="emailnotification",
            name="last_modification",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="smsnotification",
            name="last_modification",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
