# Generated by Django 4.2.1 on 2023-10-06 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_notes', '0014_alter_biometriccustomrecords_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricheightrecords',
            name='height_unit_to_present',
            field=models.CharField(default='mm', max_length=3),
        ),
        migrations.AlterField(
            model_name='biometricrecord',
            name='height_biometric_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_notes.biometricheightrecords'),
        ),
        migrations.AlterField(
            model_name='biometricrecord',
            name='weight_biometric_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_notes.biometricweightrecords'),
        ),
        migrations.AlterField(
            model_name='biometricweightrecords',
            name='weight_unit_to_present',
            field=models.CharField(default='g', max_length=3),
        ),
    ]
