apiVersion: v1
kind: Service
metadata:
  name: ahc_app_backend_service
spec:
  selector:
    app: ahc_app_backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
