# Generated by Django 6.0.5 on 2026-05-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="dietary_restrictions",
            field=models.CharField(blank=True, default=None, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="next_visit_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
