# Generated by Django 6.0.5 on 2026-05-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0002_add_next_visit_date_and_dietary_restrictions"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="breed",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="sex",
            field=models.CharField(
                blank=True, choices=[("m", "Male"), ("f", "Female")], default=None, max_length=1, null=True
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="species",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="sterilization",
            field=models.BooleanField(default=False),
        ),
    ]
