# Generated by Django 6.0.5 on 2026-06-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0004_add_animalshare_and_sharedefaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="animalshare",
            name="allow_vaccinations",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sharedefaults",
            name="allow_vaccinations",
            field=models.BooleanField(default=False),
        ),
    ]
