# Generated by Django 6.0.5 on 2026-06-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0005_add_vaccination_share_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="date_of_death",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="memorial_note",
            field=models.CharField(blank=True, default=None, max_length=2500, null=True),
        ),
    ]
